### ISSUE TITLE
when there is not enough data python will give a StopIteration

### ISSUE THREAD

**Issue by hvanderlaan** [hvanderlaan/p2000#19]
When running ``` ./p2000.py tis``` python will quit with a StopIteration exception.
This is because there are less messages than 35.

```Traceback (most recent call last):
  File "./p2000.py", line 86, in <module>
    main()
  File "./p2000.py", line 71, in main
    msg = pager.next()
StopIteration
```

**Comment by hvanderlaan** [comment]
issue fixed by adding:
```python
try:
  msg = pager.next()
except StopIteration:
  break
```
